import {
  EquipmentCategory,
  WeightType,
  MuscleGroup,
  ProgramCategory,
  ProgramLevel,
  ProgramLocation,
} from '@prisma/client';

export interface SeedEquipmentDef {
  id: string;
  name: string;
  category: EquipmentCategory;
  weightType: WeightType;
  minWeightKg: number;
  maxWeightKg: number;
  incrementKg: number;
  externalName: string;
  imageAssetName: string;
  isAvailableAtGym: boolean;
}

export interface SeedCatalogDef {
  id: string;
  externalId: string;
  name: string;
  nameEs: string;
  videoUrl: string;
  imageUrl: string;
  primaryMuscleGroup: MuscleGroup;
  targetMuscles: string[];
  secondaryMuscles: string[];
  equipmentCategory: EquipmentCategory;
  equipmentName: string;
  equipmentId?: string;
  suggestedMinReps: number;
  suggestedMaxReps: number;
  defaultRestSeconds: number;
  instructions: string[];
  exerciseTips: string[];
}

export interface SeedExerciseDef {
  id: string;
  catalogId?: string | null;
  name: string;
  order: number;
  kind: { type: 'reps'; count: number } | { type: 'duration'; seconds: number };
  imageAssetName: string;
  primaryMuscleGroup: MuscleGroup;
  requiredEquipmentId?: string | null;
  substitutionGroupId?: string | null;
  minReps: number;
  maxReps: number;
  defaultSets: number;
  restSeconds: number;
}

export interface SeedWorkoutDef {
  id: string;
  title: string;
  durationMinutes: number;
  difficulty: string;
  kcalEstimate: number;
  imageAssetName: string;
  rounds: number;
  exercises: SeedExerciseDef[];
}

export interface SeedProgramDef {
  id: string;
  title: string;
  category: ProgramCategory;
  durationWeeks: number;
  level: ProgramLevel;
  location: ProgramLocation;
  tagline: string;
  imageAssetName: string;
  workouts: SeedWorkoutDef[];
}

export const BASE_EQUIPMENT: SeedEquipmentDef[] = [
  {
    id: '88888888-8888-4888-8888-888888888881',
    name: 'Barra Olímpica y Banco Plano',
    category: EquipmentCategory.FREE_WEIGHTS,
    weightType: WeightType.BARBELL,
    minWeightKg: 20.0,
    maxWeightKg: 220.0,
    incrementKg: 2.5,
    externalName: 'barbell',
    imageAssetName: 'eq_barbell_bench',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888882',
    name: 'Juego de Mancuernas Ajustables',
    category: EquipmentCategory.FREE_WEIGHTS,
    weightType: WeightType.DUMBBELL_PAIR,
    minWeightKg: 2.0,
    maxWeightKg: 50.0,
    incrementKg: 2.0,
    externalName: 'dumbbell',
    imageAssetName: 'eq_dumbbells',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888883',
    name: 'Torre de Poleas Dual Crossover',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.CABLE,
    minWeightKg: 5.0,
    maxWeightKg: 100.0,
    incrementKg: 2.5,
    externalName: 'cable',
    imageAssetName: 'eq_cable_machine',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888884',
    name: 'Power Rack para Sentadillas',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.BARBELL,
    minWeightKg: 20.0,
    maxWeightKg: 280.0,
    incrementKg: 2.5,
    externalName: 'barbell',
    imageAssetName: 'eq_squat_rack',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888885',
    name: 'Prensa de Piernas 45 Grados',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.PLATE_LOADED,
    minWeightKg: 40.0,
    maxWeightKg: 450.0,
    incrementKg: 10.0,
    externalName: 'leverage machine',
    imageAssetName: 'eq_leg_press',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888886',
    name: 'Estación de Dominadas y Fondos',
    category: EquipmentCategory.BODYWEIGHT,
    weightType: WeightType.BODYWEIGHT,
    minWeightKg: 0.0,
    maxWeightKg: 100.0,
    incrementKg: 2.5,
    externalName: 'body weight',
    imageAssetName: 'eq_pullup_station',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888887',
    name: 'Caminadora Profesional',
    category: EquipmentCategory.CARDIO,
    weightType: WeightType.ACCESSORY,
    minWeightKg: 0.0,
    maxWeightKg: 0.0,
    incrementKg: 0.0,
    externalName: 'cardio',
    imageAssetName: 'eq_treadmill',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888888',
    name: 'Remo de Aire Concept2',
    category: EquipmentCategory.CARDIO,
    weightType: WeightType.ACCESSORY,
    minWeightKg: 0.0,
    maxWeightKg: 0.0,
    incrementKg: 0.0,
    externalName: 'cardio',
    imageAssetName: 'eq_rower',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888889',
    name: 'Kettlebells de Competición',
    category: EquipmentCategory.FREE_WEIGHTS,
    weightType: WeightType.DUMBBELL_PAIR,
    minWeightKg: 4.0,
    maxWeightKg: 48.0,
    incrementKg: 4.0,
    externalName: 'kettlebell',
    imageAssetName: 'eq_kettlebell',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-88888888888a',
    name: 'Bandas Elásticas de Resistencia',
    category: EquipmentCategory.ACCESSORY,
    weightType: WeightType.BAND,
    minWeightKg: 5.0,
    maxWeightKg: 40.0,
    incrementKg: 5.0,
    externalName: 'band',
    imageAssetName: 'eq_resistance_bands',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-88888888888b',
    name: 'Polea Alta Jalón Dorsal (Lat Pulldown)',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.FIXED_STACK,
    minWeightKg: 10.0,
    maxWeightKg: 120.0,
    incrementKg: 5.0,
    externalName: 'cable',
    imageAssetName: 'eq_lat_pulldown',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-88888888888c',
    name: 'Remo en Polea Baja Sentado',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.FIXED_STACK,
    minWeightKg: 10.0,
    maxWeightKg: 120.0,
    incrementKg: 5.0,
    externalName: 'cable',
    imageAssetName: 'eq_seated_cable_row',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-88888888888d',
    name: 'Máquina Multipower / Smith',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.BARBELL,
    minWeightKg: 15.0,
    maxWeightKg: 200.0,
    incrementKg: 2.5,
    externalName: 'smith machine',
    imageAssetName: 'eq_smith_machine',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-88888888888e',
    name: 'Máquina Extensión de Cuádriceps',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.FIXED_STACK,
    minWeightKg: 10.0,
    maxWeightKg: 110.0,
    incrementKg: 5.0,
    externalName: 'lever',
    imageAssetName: 'eq_leg_extension',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-88888888888f',
    name: 'Máquina Curl Femoral Tumbado',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.FIXED_STACK,
    minWeightKg: 10.0,
    maxWeightKg: 95.0,
    incrementKg: 5.0,
    externalName: 'lever',
    imageAssetName: 'eq_leg_curl',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888810',
    name: 'Máquina Gemelos / Elevación Talones',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.FIXED_STACK,
    minWeightKg: 15.0,
    maxWeightKg: 130.0,
    incrementKg: 5.0,
    externalName: 'lever',
    imageAssetName: 'eq_calf_raise',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888811',
    name: 'Press de Pecho en Máquina Convergente',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.FIXED_STACK,
    minWeightKg: 15.0,
    maxWeightKg: 125.0,
    incrementKg: 5.0,
    externalName: 'lever',
    imageAssetName: 'eq_chest_press_machine',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888812',
    name: 'Máquina Pec Deck & Deltoides Posterior',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.FIXED_STACK,
    minWeightKg: 10.0,
    maxWeightKg: 90.0,
    incrementKg: 5.0,
    externalName: 'leverage machine',
    imageAssetName: 'eq_pec_deck',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888813',
    name: 'Press de Hombros en Máquina',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.FIXED_STACK,
    minWeightKg: 10.0,
    maxWeightKg: 90.0,
    incrementKg: 5.0,
    externalName: 'lever',
    imageAssetName: 'eq_shoulder_press_machine',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888814',
    name: 'Banco Inclinado Ajustable',
    category: EquipmentCategory.FREE_WEIGHTS,
    weightType: WeightType.DUMBBELL_PAIR,
    minWeightKg: 2.0,
    maxWeightKg: 50.0,
    incrementKg: 2.0,
    externalName: 'dumbbell',
    imageAssetName: 'eq_incline_bench',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888815',
    name: 'Barra Z / EZ Curl Bar',
    category: EquipmentCategory.FREE_WEIGHTS,
    weightType: WeightType.BARBELL,
    minWeightKg: 10.0,
    maxWeightKg: 60.0,
    incrementKg: 2.5,
    externalName: 'ez barbell',
    imageAssetName: 'eq_ez_bar',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888816',
    name: 'Banco Scott / Predicador',
    category: EquipmentCategory.FREE_WEIGHTS,
    weightType: WeightType.BARBELL,
    minWeightKg: 10.0,
    maxWeightKg: 50.0,
    incrementKg: 2.5,
    externalName: 'ez barbell',
    imageAssetName: 'eq_preacher_bench',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888817',
    name: 'Máquina Hack Squat Inclinada',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.PLATE_LOADED,
    minWeightKg: 30.0,
    maxWeightKg: 300.0,
    incrementKg: 10.0,
    externalName: 'leverage machine',
    imageAssetName: 'eq_hack_squat',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888818',
    name: 'Máquina Abductor / Aductor',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.FIXED_STACK,
    minWeightKg: 15.0,
    maxWeightKg: 90.0,
    incrementKg: 5.0,
    externalName: 'lever',
    imageAssetName: 'eq_abductor_machine',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-888888888819',
    name: 'Banco Hip Thrust con Cinturón',
    category: EquipmentCategory.STRENGTH,
    weightType: WeightType.PLATE_LOADED,
    minWeightKg: 20.0,
    maxWeightKg: 220.0,
    incrementKg: 5.0,
    externalName: 'leverage machine',
    imageAssetName: 'eq_hip_thrust_bench',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-88888888881a',
    name: 'Bicicleta Estática de Spinning',
    category: EquipmentCategory.CARDIO,
    weightType: WeightType.ACCESSORY,
    minWeightKg: 0.0,
    maxWeightKg: 0.0,
    incrementKg: 0.0,
    externalName: 'cardio',
    imageAssetName: 'eq_spin_bike',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-88888888881b',
    name: 'Elíptica Profesional',
    category: EquipmentCategory.CARDIO,
    weightType: WeightType.ACCESSORY,
    minWeightKg: 0.0,
    maxWeightKg: 0.0,
    incrementKg: 0.0,
    externalName: 'cardio',
    imageAssetName: 'eq_elliptical',
    isAvailableAtGym: true,
  },
  {
    id: '88888888-8888-4888-8888-88888888881c',
    name: 'Esterilla de Yoga & Foam Roller',
    category: EquipmentCategory.ACCESSORY,
    weightType: WeightType.BODYWEIGHT,
    minWeightKg: 0.0,
    maxWeightKg: 0.0,
    incrementKg: 0.0,
    externalName: 'body weight',
    imageAssetName: 'eq_mat_roller',
    isAvailableAtGym: true,
  },
];

export const BASE_CATALOG: SeedCatalogDef[] = [
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa01',
    externalId: 'asc_bench_press_01',
    name: 'Press de Banca Plano con Barra',
    nameEs: 'Press de Banca Plano con Barra',
    videoUrl: 'https://cdn.exercisedb.dev/videos/bench-press.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/bench-press.webp',
    primaryMuscleGroup: MuscleGroup.CHEST,
    targetMuscles: ['pectoralis major', 'anterior deltoid'],
    secondaryMuscles: ['triceps brachii'],
    equipmentCategory: EquipmentCategory.FREE_WEIGHTS,
    equipmentName: 'barbell',
    equipmentId: '88888888-8888-4888-8888-888888888881',
    suggestedMinReps: 8,
    suggestedMaxReps: 12,
    defaultRestSeconds: 90,
    instructions: [
      'Acuéstate en el banco con los ojos alineados debajo de la barra.',
      'Agarra la barra con un agarre ligeramente más ancho que el ancho de hombros.',
      'Baja la barra de forma controlada hasta la mitad del pecho.',
      'Empuja la barra explosivamente hacia arriba extendiendo los brazos sin bloquear codos.',
    ],
    exerciseTips: [
      'Mantén los pies firmes contra el suelo durante todo el movimiento.',
      'Retrae las escápulas y mantén el pecho erguido.',
    ],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa02',
    externalId: 'asc_incline_dumbbell_press_02',
    name: 'Press Inclinado con Mancuernas',
    nameEs: 'Press Inclinado con Mancuernas',
    videoUrl: 'https://cdn.exercisedb.dev/videos/incline-dumbbell-press.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/incline-dumbbell-press.webp',
    primaryMuscleGroup: MuscleGroup.CHEST,
    targetMuscles: ['clavicular pectoralis', 'anterior deltoid'],
    secondaryMuscles: ['triceps brachii'],
    equipmentCategory: EquipmentCategory.FREE_WEIGHTS,
    equipmentName: 'dumbbell',
    equipmentId: '88888888-8888-4888-8888-888888888882',
    suggestedMinReps: 10,
    suggestedMaxReps: 12,
    defaultRestSeconds: 90,
    instructions: [
      'Ajusta el banco a unos 30-45 grados de inclinación.',
      'Sostén las mancuernas al nivel del pecho superior con palmas hacia el frente.',
      'Presiona las mancuernas hacia arriba hasta casi juntarlas arriba.',
      'Baja lentamente sintiendo el estiramiento en la porción clavicular del pectoral.',
    ],
    exerciseTips: [
      'No arquees excesivamente la zona lumbar.',
      'Mantén un recorrido suave y controlado.',
    ],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa03',
    externalId: 'asc_cable_fly_03',
    name: 'Cruce de Poleas para Pecho',
    nameEs: 'Cruce de Poleas para Pecho',
    videoUrl: 'https://cdn.exercisedb.dev/videos/cable-crossover.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/cable-crossover.webp',
    primaryMuscleGroup: MuscleGroup.CHEST,
    targetMuscles: ['pectoralis major (sternal head)'],
    secondaryMuscles: ['anterior deltoid'],
    equipmentCategory: EquipmentCategory.STRENGTH,
    equipmentName: 'cable',
    equipmentId: '88888888-8888-4888-8888-888888888883',
    suggestedMinReps: 12,
    suggestedMaxReps: 15,
    defaultRestSeconds: 60,
    instructions: [
      'Coloca las poleas a una altura media o alta y sujeta las manijas.',
      'Da un paso al frente manteniendo una postura estable y ligera inclinación del torso.',
      'Junta las manos hacia el centro con una suave flexión de codos apretando el pecho.',
      'Regresa lentamente al punto inicial sintiendo la apertura.',
    ],
    exerciseTips: ['Concéntrate en la contracción del pecho al juntar las manos.'],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa04',
    externalId: 'asc_squat_04',
    name: 'Sentadilla Trasera con Barra',
    nameEs: 'Sentadilla Trasera con Barra',
    videoUrl: 'https://cdn.exercisedb.dev/videos/barbell-squat.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/barbell-squat.webp',
    primaryMuscleGroup: MuscleGroup.LEGS,
    targetMuscles: ['quadriceps', 'gluteus maximus'],
    secondaryMuscles: ['hamstrings', 'erector spinae', 'core'],
    equipmentCategory: EquipmentCategory.STRENGTH,
    equipmentName: 'barbell',
    equipmentId: '88888888-8888-4888-8888-888888888884',
    suggestedMinReps: 6,
    suggestedMaxReps: 10,
    defaultRestSeconds: 120,
    instructions: [
      'Apoya la barra sobre los trapecios y saca la barra del rack con pies al ancho de hombros.',
      'Inhala, aprieta el abdomen y flexiona caderas y rodillas descendiendo hasta romper el paralelo.',
      'Empuja fuerte a través del centro del pie para volver a la posición erguida.',
    ],
    exerciseTips: [
      'Mantén la columna neutra y las rodillas alineadas con la punta de los pies.',
    ],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa05',
    externalId: 'asc_leg_press_05',
    name: 'Prensa de Piernas Inclinada 45°',
    nameEs: 'Prensa de Piernas Inclinada 45°',
    videoUrl: 'https://cdn.exercisedb.dev/videos/leg-press.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/leg-press.webp',
    primaryMuscleGroup: MuscleGroup.LEGS,
    targetMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipmentCategory: EquipmentCategory.STRENGTH,
    equipmentName: 'leverage machine',
    equipmentId: '88888888-8888-4888-8888-888888888885',
    suggestedMinReps: 8,
    suggestedMaxReps: 12,
    defaultRestSeconds: 90,
    instructions: [
      'Siéntate con la espalda y cadera bien pegadas al respaldo.',
      'Coloca los pies al ancho de hombros en el centro de la plataforma.',
      'Libera el seguro y baja la plataforma flexionando rodillas a 90 grados.',
      'Empuja con toda la planta del pie sin bloquear las rodillas en la cima.',
    ],
    exerciseTips: ['Nunca despegues la zona lumbar ni el coxis del asiento.'],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa06',
    externalId: 'asc_lat_pulldown_06',
    name: 'Jalón al Pecho en Polea Alta',
    nameEs: 'Jalón al Pecho en Polea Alta',
    videoUrl: 'https://cdn.exercisedb.dev/videos/lat-pulldown.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/lat-pulldown.webp',
    primaryMuscleGroup: MuscleGroup.BACK,
    targetMuscles: ['latissimus dorsi', 'rhomboids'],
    secondaryMuscles: ['biceps brachii', 'posterior deltoid'],
    equipmentCategory: EquipmentCategory.STRENGTH,
    equipmentName: 'cable',
    equipmentId: '88888888-8888-4888-8888-88888888888b',
    suggestedMinReps: 8,
    suggestedMaxReps: 12,
    defaultRestSeconds: 90,
    instructions: [
      'Ajusta la almohadilla de muslos para que tus piernas queden firmes.',
      'Toma la barra ancha con palmas hacia adelante.',
      'Tira de la barra hacia la parte superior del pecho contrayendo la espalda.',
      'Extiende los brazos lentamente de vuelta a la posición inicial.',
    ],
    exerciseTips: ['No te balancees hacia atrás excesivamente durante el jalón.'],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa07',
    externalId: 'asc_cable_row_07',
    name: 'Remo Sentado en Polea Baja',
    nameEs: 'Remo Sentado en Polea Baja',
    videoUrl: 'https://cdn.exercisedb.dev/videos/seated-cable-row.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/seated-cable-row.webp',
    primaryMuscleGroup: MuscleGroup.BACK,
    targetMuscles: ['middle back', 'latissimus dorsi', 'rhomboids'],
    secondaryMuscles: ['biceps brachii'],
    equipmentCategory: EquipmentCategory.STRENGTH,
    equipmentName: 'cable',
    equipmentId: '88888888-8888-4888-8888-88888888888c',
    suggestedMinReps: 10,
    suggestedMaxReps: 12,
    defaultRestSeconds: 90,
    instructions: [
      'Siéntate con los pies en los apoyos y rodillas ligeramente flexionadas.',
      'Agarra el maneral en V y mantén la espalda recta con el pecho erguido.',
      'Jala hacia tu abdomen juntando las escápulas.',
      'Regresa con control sin encorvar los hombros.',
    ],
    exerciseTips: [
      'Inicia el jalón retrayendo las escápulas, no tirando solo con los brazos.',
    ],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa08',
    externalId: 'asc_pullup_08',
    name: 'Dominadas Pronas / Pull-ups',
    nameEs: 'Dominadas Pronas / Pull-ups',
    videoUrl: 'https://cdn.exercisedb.dev/videos/pull-up.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/pull-up.webp',
    primaryMuscleGroup: MuscleGroup.BACK,
    targetMuscles: ['latissimus dorsi', 'teres major'],
    secondaryMuscles: ['biceps brachii', 'core'],
    equipmentCategory: EquipmentCategory.BODYWEIGHT,
    equipmentName: 'body weight',
    equipmentId: '88888888-8888-4888-8888-888888888886',
    suggestedMinReps: 6,
    suggestedMaxReps: 10,
    defaultRestSeconds: 120,
    instructions: [
      'Cuélgate de la barra con agarre en pronación ligeramente más amplio que los hombros.',
      'Inicia tirando de los codos hacia abajo y atrás elevando el pecho hacia la barra.',
      'Sube hasta que la barbilla pase la barra y desciende de forma controlada.',
    ],
    exerciseTips: ['Evita balanceos o patadas para generar inercia.'],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa09',
    externalId: 'asc_shoulder_press_09',
    name: 'Press Militar con Mancuernas',
    nameEs: 'Press Militar con Mancuernas',
    videoUrl: 'https://cdn.exercisedb.dev/videos/dumbbell-shoulder-press.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/dumbbell-shoulder-press.webp',
    primaryMuscleGroup: MuscleGroup.SHOULDERS,
    targetMuscles: ['anterior deltoid', 'lateral deltoid'],
    secondaryMuscles: ['triceps brachii', 'upper trapezius'],
    equipmentCategory: EquipmentCategory.FREE_WEIGHTS,
    equipmentName: 'dumbbell',
    equipmentId: '88888888-8888-4888-8888-888888888882',
    suggestedMinReps: 8,
    suggestedMaxReps: 12,
    defaultRestSeconds: 90,
    instructions: [
      'Siéntate en el banco con respaldo vertical sosteniendo las mancuernas a la altura de las orejas.',
      'Empuja las mancuernas verticalmente hacia arriba hasta extender los brazos.',
      'Baja controladamente hasta que las mancuernas alcancen nuevamente la altura de los hombros.',
    ],
    exerciseTips: [
      'No dejes que los codos caigan demasiado por debajo de 90 grados al descender.',
    ],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa10',
    externalId: 'asc_lateral_raise_10',
    name: 'Elevaciones Laterales con Mancuernas',
    nameEs: 'Elevaciones Laterales con Mancuernas',
    videoUrl: 'https://cdn.exercisedb.dev/videos/dumbbell-lateral-raise.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/dumbbell-lateral-raise.webp',
    primaryMuscleGroup: MuscleGroup.SHOULDERS,
    targetMuscles: ['lateral deltoid'],
    secondaryMuscles: ['anterior deltoid', 'trapezius'],
    equipmentCategory: EquipmentCategory.FREE_WEIGHTS,
    equipmentName: 'dumbbell',
    equipmentId: '88888888-8888-4888-8888-888888888882',
    suggestedMinReps: 12,
    suggestedMaxReps: 15,
    defaultRestSeconds: 60,
    instructions: [
      'De pie con una mancuerna en cada mano a los costados del cuerpo.',
      'Eleva los brazos hacia los lados con una ligera flexión de codo hasta la altura del hombro.',
      'Pausa un instante en la cima y baja lentamente controlando el peso.',
    ],
    exerciseTips: [
      'Piensa en verter agua de una jarra girando ligeramente los meñiques hacia arriba.',
    ],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa11',
    externalId: 'asc_biceps_curl_11',
    name: 'Curl de Bíceps con Barra Z',
    nameEs: 'Curl de Bíceps con Barra Z',
    videoUrl: 'https://cdn.exercisedb.dev/videos/ez-bar-curl.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/ez-bar-curl.webp',
    primaryMuscleGroup: MuscleGroup.ARMS,
    targetMuscles: ['biceps brachii', 'brachialis'],
    secondaryMuscles: ['forearms'],
    equipmentCategory: EquipmentCategory.FREE_WEIGHTS,
    equipmentName: 'ez barbell',
    equipmentId: '88888888-8888-4888-8888-888888888815',
    suggestedMinReps: 10,
    suggestedMaxReps: 12,
    defaultRestSeconds: 60,
    instructions: [
      'Toma la barra Z por las curvas interiores con agarre en supinación.',
      'Mantén los codos pegados a los costados y el pecho firme.',
      'Flexiona los codos contrayendo los bíceps hasta la altura del pecho.',
      'Baja controladamente estirando por completo el bíceps sin balancear el torso.',
    ],
    exerciseTips: ['No utilices balanceo lumbar para iniciar la repetición.'],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa12',
    externalId: 'asc_triceps_pushdown_12',
    name: 'Extensión de Tríceps en Polea con Cuerda',
    nameEs: 'Extensión de Tríceps en Polea con Cuerda',
    videoUrl: 'https://cdn.exercisedb.dev/videos/cable-tricep-pushdown.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/cable-tricep-pushdown.webp',
    primaryMuscleGroup: MuscleGroup.ARMS,
    targetMuscles: ['triceps brachii (lateral and medial heads)'],
    secondaryMuscles: [],
    equipmentCategory: EquipmentCategory.STRENGTH,
    equipmentName: 'cable',
    equipmentId: '88888888-8888-4888-8888-888888888883',
    suggestedMinReps: 12,
    suggestedMaxReps: 15,
    defaultRestSeconds: 60,
    instructions: [
      'Coloca la cuerda en la polea alta y sujeta los extremos.',
      'Mantén los codos fijos a los lados del torso.',
      'Extiende los brazos hacia abajo abriendo los extremos de la cuerda al final del recorrido.',
      'Regresa a la flexión de 90 grados con control.',
    ],
    exerciseTips: [
      'Asegúrate de que solo los antebrazos se muevan durante el ejercicio.',
    ],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa13',
    externalId: 'asc_plank_13',
    name: 'Plancha Abdominal Estática',
    nameEs: 'Plancha Abdominal Estática',
    videoUrl: 'https://cdn.exercisedb.dev/videos/plank.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/plank.webp',
    primaryMuscleGroup: MuscleGroup.CORE,
    targetMuscles: ['rectus abdominis', 'transverse abdominis'],
    secondaryMuscles: ['obliques', 'gluteus maximus'],
    equipmentCategory: EquipmentCategory.BODYWEIGHT,
    equipmentName: 'body weight',
    equipmentId: '88888888-8888-4888-8888-88888888881c',
    suggestedMinReps: 45,
    suggestedMaxReps: 60,
    defaultRestSeconds: 60,
    instructions: [
      'Colócate boca abajo apoyando los antebrazos y las puntas de los pies en el suelo.',
      'Mantén el cuerpo en una línea recta desde la cabeza hasta los talones.',
      'Activa el abdomen y los glúteos fuertemente respirando de manera fluida.',
    ],
    exerciseTips: ['No permitas que la cadera caiga ni se eleve excesivamente.'],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa14',
    externalId: 'asc_burpee_14',
    name: 'Burpees Metabólicos',
    nameEs: 'Burpees Metabólicos',
    videoUrl: 'https://cdn.exercisedb.dev/videos/burpee.mp4',
    imageUrl: 'https://cdn.exercisedb.dev/images/burpee.webp',
    primaryMuscleGroup: MuscleGroup.CARDIO,
    targetMuscles: ['full body cardiovascular system'],
    secondaryMuscles: ['quadriceps', 'chest', 'core'],
    equipmentCategory: EquipmentCategory.BODYWEIGHT,
    equipmentName: 'body weight',
    equipmentId: '88888888-8888-4888-8888-88888888881c',
    suggestedMinReps: 12,
    suggestedMaxReps: 15,
    defaultRestSeconds: 45,
    instructions: [
      'Comienza de pie, agáchate y coloca las manos en el suelo.',
      'Lanza los pies hacia atrás para quedar en posición de flexión y toca el suelo con el pecho.',
      'Regresa los pies de un salto hacia tus manos y salta verticalmente extendiendo los brazos arriba.',
    ],
    exerciseTips: [
      'Aterriza suavemente sobre las puntas de los pies absorbiendo el impacto.',
    ],
  },
];

export const BASE_PROGRAMS: SeedProgramDef[] = [
  // --- MUSCLE GAIN ---
  {
    id: '11111111-1111-4111-8111-11111111111a',
    title: 'Iniciación a la Hipertrofia',
    category: ProgramCategory.MUSCLE_GAIN,
    durationWeeks: 6,
    level: ProgramLevel.BEGINNER,
    location: ProgramLocation.GYM,
    tagline: 'Construye una base sólida de masa muscular con técnica impecable',
    imageAssetName: 'program_muscle_beginner',
    workouts: [
      {
        id: '22222222-2222-4222-8222-222222222211',
        title: 'Full Body A - Fuerza Base',
        durationMinutes: 45,
        difficulty: 'Principiante',
        kcalEstimate: 360,
        imageAssetName: 'workout_fullbody_a',
        rounds: 3,
        exercises: [
          {
            id: '33333333-3333-4333-8333-333333333101',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa05',
            name: 'Prensa de Piernas Inclinada 45°',
            order: 1,
            kind: { type: 'reps', count: 10 },
            imageAssetName: 'ex_leg_press',
            primaryMuscleGroup: MuscleGroup.LEGS,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888885',
            substitutionGroupId: 'sub_group_squat_press',
            minReps: 8,
            maxReps: 12,
            defaultSets: 3,
            restSeconds: 90,
          },
          {
            id: '33333333-3333-4333-8333-333333333102',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa01',
            name: 'Press de Banca Plano con Barra',
            order: 2,
            kind: { type: 'reps', count: 10 },
            imageAssetName: 'ex_bench_press',
            primaryMuscleGroup: MuscleGroup.CHEST,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888881',
            substitutionGroupId: 'sub_group_chest_press',
            minReps: 8,
            maxReps: 12,
            defaultSets: 3,
            restSeconds: 90,
          },
          {
            id: '33333333-3333-4333-8333-333333333103',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa06',
            name: 'Jalón al Pecho en Polea Alta',
            order: 3,
            kind: { type: 'reps', count: 12 },
            imageAssetName: 'ex_lat_pulldown',
            primaryMuscleGroup: MuscleGroup.BACK,
            requiredEquipmentId: '88888888-8888-4888-8888-88888888888b',
            substitutionGroupId: 'sub_group_back_pull',
            minReps: 10,
            maxReps: 12,
            defaultSets: 3,
            restSeconds: 90,
          },
        ],
      },
    ],
  },
  {
    id: '11111111-1111-4111-8111-111111111111',
    title: 'Hipertrofia Total - Push Pull Legs',
    category: ProgramCategory.MUSCLE_GAIN,
    durationWeeks: 8,
    level: ProgramLevel.INTERMEDIATE,
    location: ProgramLocation.GYM,
    tagline: 'Gana masa muscular magra y fuerza con progresión doble',
    imageAssetName: 'program_hypertrophy',
    workouts: [
      {
        id: '22222222-2222-4222-8222-222222222221',
        title: 'Pecho & Tríceps Power',
        durationMinutes: 50,
        difficulty: 'Intermedio',
        kcalEstimate: 420,
        imageAssetName: 'workout_chest_triceps',
        rounds: 4,
        exercises: [
          {
            id: '33333333-3333-4333-8333-333333333331',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa01',
            name: 'Press de Banca Plano con Barra',
            order: 1,
            kind: { type: 'reps', count: 10 },
            imageAssetName: 'ex_bench_press',
            primaryMuscleGroup: MuscleGroup.CHEST,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888881',
            substitutionGroupId: 'sub_group_chest_press',
            minReps: 8,
            maxReps: 12,
            defaultSets: 4,
            restSeconds: 90,
          },
          {
            id: '33333333-3333-4333-8333-333333333339',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa02',
            name: 'Press Inclinado con Mancuernas',
            order: 2,
            kind: { type: 'reps', count: 10 },
            imageAssetName: 'ex_dumbbell_bench_press',
            primaryMuscleGroup: MuscleGroup.CHEST,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888882',
            substitutionGroupId: 'sub_group_chest_press',
            minReps: 8,
            maxReps: 12,
            defaultSets: 3,
            restSeconds: 90,
          },
          {
            id: '33333333-3333-4333-8333-333333333333',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa12',
            name: 'Extensión de Tríceps en Polea con Cuerda',
            order: 3,
            kind: { type: 'reps', count: 12 },
            imageAssetName: 'ex_tricep_pushdown',
            primaryMuscleGroup: MuscleGroup.ARMS,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888883',
            substitutionGroupId: 'sub_group_triceps',
            minReps: 10,
            maxReps: 15,
            defaultSets: 3,
            restSeconds: 60,
          },
        ],
      },
      {
        id: '22222222-2222-4222-8222-222222222222',
        title: 'Pierna & Core Explosivo',
        durationMinutes: 55,
        difficulty: 'Intermedio',
        kcalEstimate: 510,
        imageAssetName: 'workout_leg_core',
        rounds: 4,
        exercises: [
          {
            id: '33333333-3333-4333-8333-333333333334',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa04',
            name: 'Sentadilla Trasera con Barra',
            order: 1,
            kind: { type: 'reps', count: 8 },
            imageAssetName: 'ex_back_squat',
            primaryMuscleGroup: MuscleGroup.LEGS,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888884',
            substitutionGroupId: 'sub_group_squat_press',
            minReps: 6,
            maxReps: 10,
            defaultSets: 4,
            restSeconds: 120,
          },
          {
            id: '33333333-3333-4333-8333-33333333333b',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa05',
            name: 'Prensa de Piernas Inclinada 45°',
            order: 2,
            kind: { type: 'reps', count: 10 },
            imageAssetName: 'ex_leg_press',
            primaryMuscleGroup: MuscleGroup.LEGS,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888885',
            substitutionGroupId: 'sub_group_squat_press',
            minReps: 8,
            maxReps: 12,
            defaultSets: 3,
            restSeconds: 90,
          },
          {
            id: '33333333-3333-4333-8333-333333333335',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa13',
            name: 'Plancha Abdominal Estática',
            order: 3,
            kind: { type: 'duration', seconds: 45 },
            imageAssetName: 'ex_plank',
            primaryMuscleGroup: MuscleGroup.CORE,
            requiredEquipmentId: null,
            substitutionGroupId: 'sub_group_core_static',
            minReps: 30,
            maxReps: 60,
            defaultSets: 3,
            restSeconds: 60,
          },
        ],
      },
    ],
  },
  {
    id: '11111111-1111-4111-8111-11111111111b',
    title: 'Hipertrofia Avanzada & Alta Intensidad',
    category: ProgramCategory.MUSCLE_GAIN,
    durationWeeks: 10,
    level: ProgramLevel.ADVANCED,
    location: ProgramLocation.GYM,
    tagline: 'Sobrecarga progresiva máxima y técnicas avanzadas de volumen',
    imageAssetName: 'program_muscle_advanced',
    workouts: [
      {
        id: '22222222-2222-4222-8222-222222222212',
        title: 'Espalda & Deltoides Posterior Intenso',
        durationMinutes: 60,
        difficulty: 'Avanzado',
        kcalEstimate: 540,
        imageAssetName: 'workout_back_shoulders',
        rounds: 4,
        exercises: [
          {
            id: '33333333-3333-4333-8333-333333333104',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa08',
            name: 'Dominadas Pronas / Pull-ups',
            order: 1,
            kind: { type: 'reps', count: 8 },
            imageAssetName: 'ex_pullup',
            primaryMuscleGroup: MuscleGroup.BACK,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888886',
            substitutionGroupId: 'sub_group_back_pull',
            minReps: 6,
            maxReps: 10,
            defaultSets: 4,
            restSeconds: 120,
          },
          {
            id: '33333333-3333-4333-8333-333333333105',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa07',
            name: 'Remo Sentado en Polea Baja',
            order: 2,
            kind: { type: 'reps', count: 10 },
            imageAssetName: 'ex_seated_cable_row',
            primaryMuscleGroup: MuscleGroup.BACK,
            requiredEquipmentId: '88888888-8888-4888-8888-88888888888c',
            substitutionGroupId: 'sub_group_back_row',
            minReps: 8,
            maxReps: 12,
            defaultSets: 4,
            restSeconds: 90,
          },
          {
            id: '33333333-3333-4333-8333-333333333106',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa10',
            name: 'Elevaciones Laterales con Mancuernas',
            order: 3,
            kind: { type: 'reps', count: 15 },
            imageAssetName: 'ex_lateral_raise',
            primaryMuscleGroup: MuscleGroup.SHOULDERS,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888882',
            substitutionGroupId: 'sub_group_shoulders_lateral',
            minReps: 12,
            maxReps: 15,
            defaultSets: 4,
            restSeconds: 60,
          },
        ],
      },
    ],
  },

  // --- WEIGHT LOSS ---
  {
    id: '11111111-1111-4111-8111-111111111112',
    title: 'Quema Grasa Express',
    category: ProgramCategory.WEIGHT_LOSS,
    durationWeeks: 4,
    level: ProgramLevel.BEGINNER,
    location: ProgramLocation.HOME,
    tagline: 'Entrenamientos dinámicos de alta intensidad y activación metabólica',
    imageAssetName: 'program_hiit',
    workouts: [
      {
        id: '22222222-2222-4222-8222-222222222223',
        title: 'HIIT Full Body',
        durationMinutes: 30,
        difficulty: 'Principiante',
        kcalEstimate: 350,
        imageAssetName: 'workout_hiit_fullbody',
        rounds: 3,
        exercises: [
          {
            id: '33333333-3333-4333-8333-333333333336',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa14',
            name: 'Burpees Metabólicos',
            order: 1,
            kind: { type: 'reps', count: 12 },
            imageAssetName: 'ex_burpees',
            primaryMuscleGroup: MuscleGroup.CARDIO,
            requiredEquipmentId: null,
            substitutionGroupId: 'sub_group_cardio_bodyweight',
            minReps: 10,
            maxReps: 15,
            defaultSets: 3,
            restSeconds: 45,
          },
          {
            id: '33333333-3333-4333-8333-333333333337',
            catalogId: null,
            name: 'Mountain Climbers',
            order: 2,
            kind: { type: 'duration', seconds: 40 },
            imageAssetName: 'ex_mountain_climbers',
            primaryMuscleGroup: MuscleGroup.CARDIO,
            requiredEquipmentId: null,
            substitutionGroupId: 'sub_group_cardio_bodyweight',
            minReps: 30,
            maxReps: 60,
            defaultSets: 3,
            restSeconds: 45,
          },
        ],
      },
    ],
  },
  {
    id: '11111111-1111-4111-8111-11111111111c',
    title: 'Definición & HIIT Dinámico',
    category: ProgramCategory.WEIGHT_LOSS,
    durationWeeks: 6,
    level: ProgramLevel.INTERMEDIATE,
    location: ProgramLocation.HOME_AND_GYM,
    tagline: 'Quema calorías acelerada combinando pesas y circuitos funcionales',
    imageAssetName: 'program_hiit_intermediate',
    workouts: [
      {
        id: '22222222-2222-4222-8222-222222222213',
        title: 'Circuito Quema Grasa con Mancuernas',
        durationMinutes: 40,
        difficulty: 'Intermedio',
        kcalEstimate: 450,
        imageAssetName: 'workout_circuit_dumbbell',
        rounds: 4,
        exercises: [
          {
            id: '33333333-3333-4333-8333-333333333107',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa09',
            name: 'Press Militar con Mancuernas',
            order: 1,
            kind: { type: 'reps', count: 12 },
            imageAssetName: 'ex_dumbbell_shoulder_press',
            primaryMuscleGroup: MuscleGroup.SHOULDERS,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888882',
            substitutionGroupId: 'sub_group_shoulder_press',
            minReps: 10,
            maxReps: 12,
            defaultSets: 4,
            restSeconds: 60,
          },
          {
            id: '33333333-3333-4333-8333-333333333108',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa14',
            name: 'Burpees Metabólicos',
            order: 2,
            kind: { type: 'reps', count: 15 },
            imageAssetName: 'ex_burpees',
            primaryMuscleGroup: MuscleGroup.CARDIO,
            requiredEquipmentId: null,
            substitutionGroupId: 'sub_group_cardio_bodyweight',
            minReps: 12,
            maxReps: 15,
            defaultSets: 4,
            restSeconds: 45,
          },
        ],
      },
    ],
  },
  {
    id: '11111111-1111-4111-8111-11111111111d',
    title: 'Acondicionamiento Metabólico Avanzado',
    category: ProgramCategory.WEIGHT_LOSS,
    durationWeeks: 8,
    level: ProgramLevel.ADVANCED,
    location: ProgramLocation.GYM,
    tagline: 'Máxima quema calórica con máquinas cardiovasculares y superseries pesadas',
    imageAssetName: 'program_hiit_advanced',
    workouts: [
      {
        id: '22222222-2222-4222-8222-222222222214',
        title: 'Remo & Fuerza Metabólica',
        durationMinutes: 45,
        difficulty: 'Avanzado',
        kcalEstimate: 520,
        imageAssetName: 'workout_rower_strength',
        rounds: 4,
        exercises: [
          {
            id: '33333333-3333-4333-8333-333333333109',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa05',
            name: 'Prensa de Piernas Inclinada 45°',
            order: 1,
            kind: { type: 'reps', count: 15 },
            imageAssetName: 'ex_leg_press',
            primaryMuscleGroup: MuscleGroup.LEGS,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888885',
            substitutionGroupId: 'sub_group_squat_press',
            minReps: 12,
            maxReps: 15,
            defaultSets: 4,
            restSeconds: 60,
          },
        ],
      },
    ],
  },

  // --- HEALTH & RESISTANCE ---
  {
    id: '11111111-1111-4111-8111-111111111113',
    title: 'Movilidad & Salud Total',
    category: ProgramCategory.HEALTH,
    durationWeeks: 4,
    level: ProgramLevel.BEGINNER,
    location: ProgramLocation.HOME_AND_GYM,
    tagline: 'Mejora tu postura, flexibilidad, vitalidad y salud articular diaria',
    imageAssetName: 'program_health',
    workouts: [
      {
        id: '22222222-2222-4222-8222-222222222224',
        title: 'Movilidad y Flexibilidad',
        durationMinutes: 25,
        difficulty: 'Principiante',
        kcalEstimate: 160,
        imageAssetName: 'workout_mobility',
        rounds: 2,
        exercises: [
          {
            id: '33333333-3333-4333-8333-333333333338',
            catalogId: null,
            name: 'Cat-Cow Stretch',
            order: 1,
            kind: { type: 'duration', seconds: 60 },
            imageAssetName: 'ex_cat_cow',
            primaryMuscleGroup: MuscleGroup.BACK,
            requiredEquipmentId: null,
            substitutionGroupId: 'sub_group_mobility',
            minReps: 30,
            maxReps: 60,
            defaultSets: 2,
            restSeconds: 30,
          },
        ],
      },
    ],
  },
  {
    id: '11111111-1111-4111-8111-11111111111e',
    title: 'Fuerza Funcional & Longevidad',
    category: ProgramCategory.HEALTH,
    durationWeeks: 8,
    level: ProgramLevel.INTERMEDIATE,
    location: ProgramLocation.HOME_AND_GYM,
    tagline: 'Fuerza articular, estabilidad de core y resistencia postural duradera',
    imageAssetName: 'program_health_intermediate',
    workouts: [
      {
        id: '22222222-2222-4222-8222-222222222215',
        title: 'Estabilidad de Core & Espalda',
        durationMinutes: 35,
        difficulty: 'Intermedio',
        kcalEstimate: 280,
        imageAssetName: 'workout_core_back',
        rounds: 3,
        exercises: [
          {
            id: '33333333-3333-4333-8333-333333333110',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa13',
            name: 'Plancha Abdominal Estática',
            order: 1,
            kind: { type: 'duration', seconds: 60 },
            imageAssetName: 'ex_plank',
            primaryMuscleGroup: MuscleGroup.CORE,
            requiredEquipmentId: null,
            substitutionGroupId: 'sub_group_core_static',
            minReps: 45,
            maxReps: 60,
            defaultSets: 3,
            restSeconds: 60,
          },
          {
            id: '33333333-3333-4333-8333-333333333111',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa07',
            name: 'Remo Sentado en Polea Baja',
            order: 2,
            kind: { type: 'reps', count: 12 },
            imageAssetName: 'ex_seated_cable_row',
            primaryMuscleGroup: MuscleGroup.BACK,
            requiredEquipmentId: '88888888-8888-4888-8888-88888888888c',
            substitutionGroupId: 'sub_group_back_row',
            minReps: 10,
            maxReps: 12,
            defaultSets: 3,
            restSeconds: 60,
          },
        ],
      },
    ],
  },
  {
    id: '11111111-1111-4111-8111-11111111111f',
    title: 'Atleta Híbrido: Resistencia & Potencia',
    category: ProgramCategory.HEALTH,
    durationWeeks: 12,
    level: ProgramLevel.ADVANCED,
    location: ProgramLocation.GYM,
    tagline: 'Capacidad aeróbica extrema combinada con levantamientos compuestos',
    imageAssetName: 'program_health_advanced',
    workouts: [
      {
        id: '22222222-2222-4222-8222-222222222216',
        title: 'Resistencia Muscular Total',
        durationMinutes: 50,
        difficulty: 'Avanzado',
        kcalEstimate: 480,
        imageAssetName: 'workout_hybrid_athlete',
        rounds: 4,
        exercises: [
          {
            id: '33333333-3333-4333-8333-333333333112',
            catalogId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa04',
            name: 'Sentadilla Trasera con Barra',
            order: 1,
            kind: { type: 'reps', count: 12 },
            imageAssetName: 'ex_back_squat',
            primaryMuscleGroup: MuscleGroup.LEGS,
            requiredEquipmentId: '88888888-8888-4888-8888-888888888884',
            substitutionGroupId: 'sub_group_squat_press',
            minReps: 10,
            maxReps: 12,
            defaultSets: 4,
            restSeconds: 90,
          },
        ],
      },
    ],
  },
];
